### ISSUE TITLE
Dragging image into new note locks the note

### ISSUE THREAD

**Issue by msbentley** [nvbn/everpad#146]
If I create a new note, and drag an image in, I indeed see the image appear. But the note is then locked (I cannot edit, add text, delete anything etc.).  If I then try to save and close the note, it vanishes (not in the note list, not sync'd).

**Comment by mhaggag** [comment]
The editor is a QWebPage (a Webkit control, essentially). I had a suspicion that the issue is a redirection to the URL of the dragged image, and I confirmed it by hooking up the QWebPage.mainFrame.urlChanged signal to a slot and printing out the URL.

When you drag the image into the note, the URL gets changed into something like file:///path/to/image.png, which is why it's no longer editable.

Everpad should either disable navigating to a different URL (i.e. prevent drag/drop of images/files) or handle the drag/drop by inserting the content into the note.
